# Generated by Django 4.2.11 on 2024-05-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_vendor_average_response_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
